### ISSUE TITLE
Extra card next to card with specific label

### ISSUE THREAD

**Issue by coopjakob** [coopjakob/memory#10]
Labels is found as an array in
`placements[0].products.productLabels` and the ID of the label is found as `code`. It can be "alltidlagtpris", "EKO_SV", "KRAV0U0MARK", "EU0U0ORGANIC0U0FARMING" etc.

If label is being specified in the "buddy card" (ad or info card) we need to find when the first card with this label is shown, and show the card before this card, if not another buddy card is already added, if so, skip and find the next.

See info cards at #9 to know where to look for matching labels. Same support needs to be added to ad cards too.

**Comment by coopjakob** [comment]
![Screenshot 2020-02-27 at 16 05 56](https://user-images.githubusercontent.com/59063397/75456625-0e0ffe00-597b-11ea-9bd3-48e6a29a4fc3.png)

**Comment by benjick** [comment]
> Notice! If the product card is the last one in a row. We don't want to add it as the card before, because then the product card will be pushed to the next row. If this happens we want to get more space at the end of the row by rearrange the cards and change place with the previous card, then it will end up at the next row. ***(should this be a separate issue maybe?)***

Yes please!

**Comment by coopjakob** [comment]
> Yes please!

#13

**Comment by benjick** [comment]
Fixed in https://github.com/benjick/kenora-thistles-nuxt/pull/6/

**Comment by benjick** [comment]
Done in #15
