### ISSUE TITLE
Add to cart and update quantity from product card

### ISSUE THREAD

**Issue by coopjakob** [coopjakob/memory#3]
The add to cart is already on coop.se so we don't need to fully recreate it.

To enable it we need to have the right css in the right places. Maybe use the same structure of the html elements as on coop.se/handla, but it might also be a bit too bloated (don't know)

I think the rules is like this:
1. js-qty-selector-plus and js-qty-selector-minus must be placed on buttons to add and remove number of products.
2. Input field need the name js-qty-selector-input
3. input also need `data-max=999`
4. `.add-to-cart` class need:
``` 
         :data-product="id"
          data-category-lvl-1="0"
          data-category-lvl-3="0"
```
5. Two levels up from `js-qty-selector-plus` and -minus you also need data from step 4, so these should be the same div.
6. Use `js-qty-selector` to wrap things, can't remember exactly how it needs to be (can be investigated)

If this is implemented correctly the first add to cart will correctly trigger the "enter your zip code" dialog box.

Warning! The functionality of the buttons on coop.se/handla (Hybris CMS) is generated by jQuery, and it might be that it only works as long as the jQuery is triggered after our code is generated. If we remove other (original) product placements on the page it might not be triggered, or if we generate new cards etc.

**Comment by benjick** [comment]
This is now done in #24, but I wonder about the "Add to cart" button - should I remove it from the code?

**Comment by coopjakob** [comment]
> I wonder about the "Add to cart" button - should I remove it from the code?

The big "Add to cart" button should only be visible for mobile/tablet users. I think it's now correctly implemented in kenora-thistles and we can use the same solution in memory. I fixed it recently.

here:
https://github.com/coopjakob/kenora-thistles/commit/47663f5b1a50e4cc5e67ac1e5fd51f52d843c8ad

and:
https://github.com/coopjakob/kenora-thistles/commit/c48a02ea6c9a5e5079924d9e6f162a80b22d3349#diff-b9c37640af91cf3c88f8fa0a8cda2d81R394
