### ISSUE TITLE
Limited audience for extra cards

### ISSUE THREAD

**Issue by coopjakob** [coopjakob/memory#38]
In `window.ACC.config` we will find these settings:

```
storeName: "STOCKHOLM"
user: "anonymous"
b2bUser: false
postCode: undefined
```

We will need to use these settings to limit extra cards to these audiences:

1. Logged in or logged out, using "include: [user: anonymous]"
2. Only one store and not default store, using "include: [storeName: X], exclude: [postCode: undefined]
3. Only companies, using "include: [b2bUser: false]

This can be structured adding a flexible solution with config/settings to each card. This massive example shows an add for anonymous user, in Stockholm store, but not if they are B2B or if they haven't selected zip code. Using this structure, we can also use "hasSavedCarts: true" etc without further development.
```
include: {
  user: "anonymous",
  storeName: "STOCKHOLM",
  // storeName: "GÖTEBORG" removed from scope
},
exclude: {
  b2bUser: true,
  postCode: undefined
}
```

**Comment by benjick** [comment]
I'll fix it. 

What happens if these settings are not present?

**Comment by benjick** [comment]
And is this the syntax we want?

```js
include: [{
  user: "anonymous",
  storeName: "STOCKHOLM"
}, {
  storeName: "GÖTEBORG"
}],
exclude: [{
  b2bUser: true,
  postCode: undefined
}]
```

**Comment by benjick** [comment]
I'm thinking we could have something like this instead:

```js
include: {
  user: "anonymous",
  storeName: ["STOCKHOLM", GÖTEBORG]
},
exclude: {
  b2bUser: true,
  postCode: undefined
}
```

**Comment by coopjakob** [comment]
Multiple values for one config is not included in current solution, because it makes things more complicated and it might not be needed.

Current solution also uses ConfigState type.
