### ISSUE TITLE
Sync products in cart and quantity on card

### ISSUE THREAD

**Issue by coopjakob** [coopjakob/memory#4]
The current cart might be saved in:
COOP.minicart.cartData.entries

If data exist here, the quantity need to be updated to the product card and kept updated.

Below is a not so optimised way of doing it per product card:
```
        let index = COOP.minicart.cartData.entries.findIndex(
          (entry: any) => entry.product.code === this.id
        );
```
...
`return COOP.minicart.cartData.entries[index].quantity;`

For testing purposes we might not want to rely on data from an external place, so mock data or some dev settings might be a good idea.

**Comment by benjick** [comment]
```
COOP.minicart.cartData.entries.find(
  (entry: any) => entry.product.code === this.id
).quantity;
```

**Comment by coopjakob** [comment]
Looks good, will try to add it.

**Comment by coopjakob** [comment]
I currently run this for each product card to see if the specific product is in the cart. Would it be better with another solution or is it ok? Maybe loop through the cart once and update all products found in the cart, instead, or doing a more reactive solution...

**Comment by coopjakob** [comment]
> With `find` we can do it in one pass
> 
> ```
> COOP.minicart.cartData.entries.find(
>   (entry: any) => entry.product.code === this.id
> ).quantity;
> ```

Object is possibly 'undefined'.
Error in render: "TypeError: Cannot read property 'quantity' of undefined"

This is the full code we're replacing:
```
        let index = COOP.minicart.cartData.entries.findIndex(
          (entry: any) => entry.product.code === this.id
        );

        window.console.debug("index:", index);

        if (index > -1) {
          window.console.debug("quantity exist in cart product, get old");
          return COOP.minicart.cartData.entries[index].quantity;
        } else {
          return 0;
        }
```

The problem is that `quantity` not always exist. Do we need lodash?

**Comment by benjick** [comment]
I think we can do it like this:

```

**Comment by coopjakob** [comment]
```
        let tempasasd = COOP.minicart.cartData.entries.find(
        (entry: any) => entry?.product?.code === this.id
        )?.quantity;
```

Maybe when adding a `?` on the last line?
Before I got `Object is possibly 'undefined'` error.

Unfortunately my test environment is broken, so I can only test things live on coop.se now.

**Comment by coopjakob** [comment]
```
error: Parsing error: Expression expected at src/components/ProductCard.vue:185:30:
  183 | 
  184 |         return COOP.minicart.cartData.entries.find(
> 185 |         (entry: any) => entry?.product?.code === this.id
      |                              ^
  186 |         )?.quantity;
```

**Comment by coopjakob** [comment]
Oh, maybe `?` is not supported in my installation. How did you enable it?

**Comment by coopjakob** [comment]
Or in lint.
